# Advanced Numpy
# 1. Insert

In [2]:
"""
np.insert(array, index , value, asix=None)
array - original array
index -
Value -
axis -
axis = 0, row wise
axis = 1, column wise 
"""
import numpy as np
arr = np.array([10,20,30,40,50,60])
new_arr = np.insert(arr,2,100,axis=0) # 30 ko change krke ussme 100 dlna hai hume theek 
print(new_arr)

[ 10  20 100  30  40  50  60]


In [ ]:
print("Before Inserting")
arr_2d = np.array([[10,20],[30,40]])
print(arr_2d)
print("After inserting")
new_arr = np.insert(arr_2d,1,[5,6],axis = 1)
print(new_arr) # agr axis ki value zero kr doge toh ye array ke flaten version me fill kr dega 


Before Inserting
[[10 20]
 [30 40]]
After inserting
[[10  5 20]
 [30  6 40]]


# Append.py

In [12]:
arr = np.array([20,30,40,50])
new_arr = np.append(arr,[40,50,60])
print(new_arr)

[20 30 40 50 40 50 60]


# concatenate((array1,array2),axis = 0)

In [15]:
"""
axis 0 > vertical stacking
axis 1 > horizontal stacking
"""
arr1 = np.array([20,30,40])
arr2 = np.array([20,30,40])
new_array = np.concatenate((arr1,arr2))
print(new_array)

[20 30 40 20 30 40]


# np.delete.py


In [16]:
arr = np.array([10,20,30,40])
new_array =np.delete(arr,1)
print(new_array)

[10 30 40]


In [17]:
arr_2d = np.array([[10,20],[30,40]])
new_array_2d = np.delete(arr_2d,1,axis = 0)
print(new_array_2d)

[[10 20]]


# Stacking.py

In [19]:
"""
vstack() row wise
hstack() column wise
"""
arr1 = np.array([20,30,40])
arr2 = np.array([20,30,40])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))


[[20 30 40]
 [20 30 40]]
[20 30 40 20 30 40]


# splitting.py


In [24]:
"""
np.split
equal
np.hsplit
np.vsplit
"""
arr = np.array([10,20,30,40,50,60])
print(np.split(arr,2))

[array([10, 20, 30]), array([40, 50, 60])]
