# Creating arrays from python list

In [ ]:
import numpy as np
arr_1d = np.array([10,20,30,40,50])
print(arr_1d)


[10 20 30 40 50]


In [3]:
#with default values 
zeroes_array = np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [4]:
#ones(shape)
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#full_(shape,value)
filled_arr = np.full((2,2),7)
print(filled_arr)

[[7 7]
 [7 7]]


In [ ]:
#creating sequesnce of number in numpy
#arange ()
#arange(start,top,step)
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [10]:
#creaating identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
