# Broadcasting

In [4]:
# Without adding numpy hum phle dkhte hai ki ye loop se kaise hota hai 
prices = [200,260,270]
discount = 10 #10 perecnt ka discount ho rha hai man lo theek bhai 
final_prices = []
for price in prices:
    final_price = price - (price*discount/100)
    final_prices.append(final_price)
    print(final_prices)

    ## numpy se hum aaise kam without using any loop iss kam ko bhautt easly kr skte hai 

[180.0]
[180.0, 234.0]
[180.0, 234.0, 243.0]


In [6]:
## using numpy
import numpy as np
prices = np.array([200,260,270])
discount = 10
final_prices = prices - (prices*discount/100)
print(final_prices)



[180. 234. 243.]


# how numpy handlle rray of diffrent shapes

In [7]:
## 
arr = np.array([200,260,270])
result = arr*2
print(result)

[400 520 540]


In [ ]:
## 1d to 2d array broadcasting
matrix = np.array([[20,30,40],[40,50,60]])
vector = np.array([12,13,14])
result = matrix+vector
print(result) ## dimenssion same hona chaiye theek 

[[32 43 54]
 [52 63 74]]


# error.py

In [ ]:
matrix = np.array([[20,30,40],[40,50,60]])
vector = np.array([12,13,14,15]) ## shape yha pr 4 ho gya hai 
result = matrix+vector
print(result)
## issko hum reshape krke kr skte hai 

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

# Vectrization

In [ ]:
list1 = [1,2,3]
list2 = [4,5,6]
result = [x+y for x,y in zip(list1,list2)]
print(result)
## agr hum bdi list se kam karnege toh ye thoda slow ho jayega issliye hum numpy ka use karnege okay 

[5, 7, 9]


In [14]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 +arr2
print(result)


[5 7 9]


In [15]:
arr1 = np.array([1,2,3])
multiplied = arr*3
print(multiplied)

[600 780 810]


In [ ]:
"""
Broadcasting
expand smaller to larger 
faster then loop 
1d ko 2d me expand kar deta hai 
Vectroziation 
100 times faster than loops 
matrix iperation me 
 

"""