# Indexing Slicing
# indexing
# array[index] # oneD array
# array [row ,column] # TwoD array

In [1]:
#ek element access krna hai toh indexing agr 1 se jda element access krna hai toh slicing
import numpy as np
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[1])
print(arr[-1])



10
20
40


# slicing


In [4]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:4]) #issme hum negative step bhi pass kr skte hai 
print(arr[:4])
print(arr[::2]) #iska mtlb ye har second element ko pic krega
print(arr[::-1])


[20 30 40]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


# fancy indexing

In [7]:
arr = np.array([10,20,30,40,50,60])
print(arr[[0,2,4]]) #it is called fancy indexing

[10 30 50]


# filtiring 

In [8]:
arr = np.array([10,20,30,40,50,60])
print(arr[arr > 25]) # iska mtlb 25 se bde sare element print kra do 

[30 40 50 60]


# reshaping and mainuplating

In [11]:
# this is use when 1d array convert in 2d and 2d array convert to 3d then we will use reshaping
arr = np.array([10,20,30,40,50,60]) # inhe reshape tbhi kr kste hai jab dimenssions same ho 
reshaped_Arr = arr.reshape(2,3)
print(reshaped_Arr) # reshape does not create copy it is return of view 

[[10 20 30]
 [40 50 60]]


# flanting array 

In [13]:
"""
.ravel() -> views
.flatten() -> copy
"""
arr_2d = np.array([[12,22,33,44],[22,33,44,55]])
print(arr_2d.ravel)
print(arr_2d.flatten)

<built-in method ravel of numpy.ndarray object at 0x10ee0d230>
<built-in method flatten of numpy.ndarray object at 0x10ee0d230>
