# Creating arrays from python list

In [1]:
import numpy as np
arr_1d = np.array([10,20,30,40,50])
print(arr_1d)

[10 20 30 40 50]


In [2]:
#with default values 
zeroes_array = np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [3]:
#ones(shape)
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
#full_(shape,value)
filled_arr = np.full((2,2),7)
print(filled_arr)

[[7 7]
 [7 7]]


In [5]:
#creating sequesnce of number in numpy
#arange ()
#arange(start,top,step)
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [6]:
#creaating identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
import numpy as np 
## random integer array
arr2 = np.array([12,13,14,15,16,])

def random_integer_array(arr): ## function to calculate mean,median,std
    return np.mean(arr),np.median(arr),np.std(arr)

mean,median,std = random_integer_array(arr2)
print("Mean:",mean)
print("Median:",median)
print("Standard Deviation:",std)


Mean: 14.0
Median: 14.0
Standard Deviation: 1.4142135623730951


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
