# Numpy array properties

In [1]:
#way to find shape of array
import numpy as np
arr_2d = np.array([[10,20,30,40],[10,20,30,40]])
print(arr_2d)
print(arr_2d.shape)

[[10 20 30 40]
 [10 20 30 40]]
(2, 4)


In [4]:
#way to find size
arr_2d = np.array([[10,20,30,40],[10,20,30,40]])
print(arr_2d.size)

8


In [8]:
#waay to find dimension of array 
import numpy as np
arr_1d = np.array([10,20,30,40])
arr_2d = np.array([[10,20,30,40],[10,20,30,40]])
arr_3d = np.array([[[10,20,30,40],[10,20,30,40]]])
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [ ]:
#data type of element
arr = np.array([10,20,20.5,11])
print(arr.dtype)

float64


In [ ]:
#data type conversion
arr = np.array([1.2,1.3,1.5])
print(arr.dtype)
#conversing float to int
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)

float64
[1 1 1]
int64


# Mathematical operation in numpy

In [19]:
arr = np.array([10,20,30,40])
#addition
print(arr+5)
#substration
print(arr-5)
#multiplication
print(arr*2)
#square
print(arr**2)
#division
print(arr/2)

[15 25 35 45]
[ 5 15 25 35]
[20 40 60 80]
[ 100  400  900 1600]
[ 5. 10. 15. 20.]


In [20]:
#aggregation unction means avrg heigh price lowest price
# np.sum(arr) = add all
# np.mean(arr) = avrg
# np.max(arr) = max value 
# np.min(arr) = min val
# np.std(arr) = standerd deviation
# np.var(arr) = varience 
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))



150
30.0
50
10
14.142135623730951
200.0
