# Numpy chapter 1

In [1]:
# one dimensional array
import numpy as np
arr_1d = np.array([10,20,30,40,50])
print(arr_1d)

[10 20 30 40 50]


In [3]:
#two dimensional array
arr_2d = np.array([[10,20,30,40,50],
[50,60,70,80,90],[10,20,30,40,50]])
print(arr_2d)

[[10 20 30 40 50]
 [50 60 70 80 90]
 [10 20 30 40 50]]


In [ ]:
#multi dimensional array
matrix = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(matrix)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [ ]:
"""
file opening mode:
'r' - read mode
'w' - write mode
'a' - append mode
'r+' - read and write mode
'w+' - write and read mode
'a+' - append and read mode
"""
"""




"""